name: detectderm_app
description: Skin Disease Detection App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  tflite_flutter: ^0.10.4
  image: ^4.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/models/